version: '3.8'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"

    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_STATS_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_STATS_USERNAME=stats
      - SPRING_DATASOURCE_STATS_PASSWORD=stats
    restart: on-failure

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats
    volumes:
      - stats-db:/var/lib/postgresql/data
    restart: on-failure

  ewm-service:
    build: ./ewm-main-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_EWM_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_EWM_USERNAME=ewm
      - SPRING_DATASOURCE_EWM_PASSWORD=ewm

    restart: on-failure

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm

    volumes:
      - ewm-db:/var/lib/postgresql/data
    restart: on-failure

volumes:
  stats-db:
  ewm-db: